# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  initial:
    # Specify the execution environment.
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Initial"
          command: "echo Hi!"

  # Add a new job for running the Dependency-Check
  dependency-check:
    docker:
      - image: circleci/openjdk:17
    steps:
      - checkout
      - run:
          name: "Install Maven"
          command: sudo apt-get update && sudo apt-get install -y maven
      - run:
          name: "Run Dependency-Check"
          command: |
            mvn org.owasp:dependency-check-maven:check

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  init-workflow:
    jobs:
      - initial
      # Add the dependency-check job to the workflow
      - dependency-check:
          requires:
            - initial